### ISSUE TITLE
Kippo startup error

### ISSUE THREAD

**Issue by abhinavbom** [andrewmichaelsmith/honeypot-setup-script#26]
Following error was reported by the script while attempting to start kippo
- Starting the process kippo                                                                                                                                                        Unhandled Error
  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
  --- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 203, in loadValueFromFile
    fileObj = open(filename, mode)
  exceptions.IOError: [Errno 2] No such file or directory: '/opt/kippo/kippo.tac'

Failed to load application: [Errno 2] No such file or directory: '/opt/kippo/kippo.tac'

**Comment by xdep** [comment]
Hi abhinavbom,

it is missing the file kippo.tac,  can grab a copy from : https://github.com/andrew-morris/kippo_threatstream/blob/master/kippo.tac

Good luck

**Comment by abhinavbom** [comment]
Thanks for the reply. Which directory shall I add this file to ?

**Comment by xdep** [comment]
to /opt/kippo/

**Comment by andrewmichaelsmith** [comment]
@abhinavbom any errors printed out when you ran the script in the first place? It should just work without any manual twiddling afterwards.

@landmanmanc have you experienced this problem too?

**Comment by xdep** [comment]
Hey Andrew, as far i know it worked fine after cloning, but it was some time ago.

**Comment by abhinavbom** [comment]
@andrewmichaelsmith  On the first run of the script, all honeypots started except Kippo. 
The error log pasted in the first message is what I got.
I have added the kippo.tac file to /opt/kippo.
This time its reporting invalid syntax: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
exceptions.SyntaxError: invalid syntax (kippo.tac, line 4)

Failed to load application: invalid syntax (kippo.tac, line 4)

**Comment by abhinavbom** [comment]
getting the same error with this tac file:
https://github.com/desaster/kippo/blob/master/kippo.tac

**Comment by abhinavbom** [comment]
Got things working.

**Comment by andrewmichaelsmith** [comment]
@abhinavbom Did you run the script again and it worked or did you work round the issue?

**Comment by abhinavbom** [comment]
Managed a work round. Tried multiple things in span of days so tough to
summarize. There was some issue at my end as well like directory
permissions etc.
managed to get things working.

Thanks

On Tuesday, August 25, 2015, Andrew Smith notifications@github.com wrote:

> @abhinavbom https://github.com/abhinavbom Did you run the script again
> and it worked or did you work round the issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andrewmichaelsmith/honeypot-setup-script/issues/26#issuecomment-134517168
> .

## 

Thanks & Regards
Abhinav singh
